---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-terraform-provider-elasticstack
  description: Buildkite Pipeline for terraform-provider-elasticstack
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/terraform-provider-elasticstack

spec:
  type: buildkite-pipeline
  owner: group:control-plane-stateful-applications
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: terraform-provider-elasticstack
    spec:
      repository: elastic/terraform-provider-elasticstack
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        # your-team:
        #  access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
